/* SCRIPT FÍSICO - Banco de dados Detran

   Autor: Arthur Choi Braga
   Data: 04/11/2025

   Descrição: Script para criação das tabelas do banco de dados do Detran.
*/

CREATE TABLE PROPRIETARIO (
    cpf VARCHAR(11) PRIMARY KEY,
    nome VARCHAR(30),
    dataNascimento DATE,
    telefone VARCHAR(11),
    sexo CHAR(1),
    rua VARCHAR(50),
    numero VARCHAR(5),
    cep VARCHAR(8),
    bairro VARCHAR(30),
    cidade VARCHAR(30),
    estado VARCHAR(30),
    CONSTRAINT CHK_PROPRIETARIO_sexo CHECK (sexo IN ('M', 'F'))
);

CREATE TABLE VEICULO (
    placa VARCHAR(7) PRIMARY KEY,
    chassi VARCHAR(17),
    cor VARCHAR(30),
    anoFabricacao DATE,
    FK_PROPRIETARIO_cpf VARCHAR(11)
);

CREATE TABLE MODELO (
    numeroModelo NUMERIC PRIMARY KEY,
    nomeModelo VARCHAR(50)
);

CREATE TABLE CATEGORIA (
    numeroCategoria NUMERIC PRIMARY KEY,
    nomeCategoria VARCHAR(50)
);

CREATE TABLE INFRACAO (
    idInfracao NUMERIC PRIMARY KEY,
    dataHora DATETIME,
    velocidadeAferida NUMERIC,
    FK_VEICULO_placa VARCHAR(7),
    FK_AGENTE_matricula NUMERIC,
    FK_TIPOINFRACAO_numeroInfracao NUMERIC,
    FK_LOCAL_latitudeLongitude VARCHAR(18)
);

CREATE TABLE TIPOINFRACAO (
    numeroInfracao NUMERIC PRIMARY KEY,
    valor NUMERIC,
    descricaoInfracao VARCHAR(50)
);

CREATE TABLE LOCAL (
    latitudeLongitude VARCHAR(18) PRIMARY KEY,
    velocidadePermitida NUMERIC
);

CREATE TABLE AGENTE (
    matricula NUMERIC PRIMARY KEY,
    nome VARCHAR(50),
    dataContratacao DATE
);

CREATE TABLE tem_VEICULO_MODELO_CATEGORIA (
    fk_VEICULO_placa VARCHAR(7) PRIMARY KEY,
    fk_MODELO_numeroModelo NUMERIC,
    fk_CATEGORIA_numeroCategoria NUMERIC
);
 
ALTER TABLE VEICULO ADD CONSTRAINT FK_VEICULO_2
    FOREIGN KEY (FK_PROPRIETARIO_cpf)
    REFERENCES PROPRIETARIO (cpf)
    ON DELETE CASCADE;
 
ALTER TABLE INFRACAO ADD CONSTRAINT FK_INFRACAO_2
    FOREIGN KEY (FK_VEICULO_placa)
    REFERENCES VEICULO (placa)
    ON DELETE CASCADE;
 
ALTER TABLE INFRACAO ADD CONSTRAINT FK_INFRACAO_3
    FOREIGN KEY (FK_AGENTE_matricula)
    REFERENCES AGENTE (matricula)
    ON DELETE SET NULL;
 
ALTER TABLE INFRACAO ADD CONSTRAINT FK_INFRACAO_4
    FOREIGN KEY (FK_TIPOINFRACAO_numeroInfracao)
    REFERENCES TIPOINFRACAO (numeroInfracao)
    ON DELETE NO ACTION;
 
ALTER TABLE INFRACAO ADD CONSTRAINT FK_INFRACAO_5
    FOREIGN KEY (FK_LOCAL_latitudeLongitude)
    REFERENCES LOCAL (latitudeLongitude)
    ON DELETE NO ACTION;
 
ALTER TABLE tem_VEICULO_MODELO_CATEGORIA ADD CONSTRAINT FK_tem_VEICULO_MODELO_CATEGORIA_1
    FOREIGN KEY (fk_VEICULO_placa)
    REFERENCES VEICULO (placa)
    ON DELETE CASCADE;
 
ALTER TABLE tem_VEICULO_MODELO_CATEGORIA ADD CONSTRAINT FK_tem_VEICULO_MODELO_CATEGORIA_2
    FOREIGN KEY (fk_MODELO_numeroModelo)
    REFERENCES MODELO (numeroModelo)
    ON DELETE NO ACTION;
 
ALTER TABLE tem_VEICULO_MODELO_CATEGORIA ADD CONSTRAINT FK_tem_VEICULO_MODELO_CATEGORIA_3
    FOREIGN KEY (fk_CATEGORIA_numeroCategoria)
    REFERENCES CATEGORIA (numeroCategoria)
    ON DELETE NO ACTION;